
import os
from common_utils import clear_console,type_text
from paths import AGREEMENT_FILE
from terminal_colors import (
    RED,
    BOLD,
    LIGHT_YELLOW,
    RESET
)


def check_agreement():
    if not os.path.exists(AGREEMENT_FILE):
        return False

    with open(AGREEMENT_FILE, "r") as file:
        return file.read().strip() == "True"


def save_agreement():
    with open(AGREEMENT_FILE, "w") as file:
        file.write("True")


def show_greeting():
    type_text("Welcome to the Property Investment Calculator!")
    type_text("Please read and accept the limitation agreement to continue.")


def agreement_text():
    return (
        "\n⚠️ Property Investment Calculator – Disclaimer & Usage Scope ⚠️\n\n"
        "Before using this tool, you must read and accept the following terms:\n\n"

        "1. Purpose of This Tool\n"
        "This calculator is designed for educational and analytical purposes only. "
        "It provides numerical analysis and insights based on user inputs and simplified financial logic. "
        "It does not confirm, validate, or guarantee the quality of any property deal.\n\n"

        "2. Insight, Not Advice\n"
        "All outputs generated by this tool are insights derived from calculations. "
        "They are not financial, legal, investment, or professional advice. "
        "No output should be interpreted as a recommendation, instruction, or decision guidance.\n\n"

        "3. Geographic and Data Limitations\n"
        "The logic and assumptions used in this tool are based on Indian real estate conditions, "
        "with primary relevance to Surat, Gujarat. "
        "Real estate markets vary significantly by location, regulation, and time. "
        "If you are operating outside this context, results may not be applicable.\n\n"

        "4. Decision Responsibility\n"
        "This tool must not be used as the sole basis for buying, selling, or negotiating any property. "
        "All property-related decisions, actions, and risks are entirely the responsibility of the user. "
        "The creator of this tool is not responsible for financial losses, missed opportunities, or outcomes.\n\n"

        "5. External Factors Not Modeled\n"
        "This calculator does not account for several real-world factors, including but not limited to:\n"
        "   - Local market behavior and liquidity\n"
        "   - Political and government policy changes\n"
        "   - Legal, zoning, or regulatory issues\n"
        "   - Individual negotiation dynamics\n"
        "   - Macroeconomic or unforeseen events\n\n"

        "6. Project Nature\n"
        "This project has been developed by a student as a learning exercise. "
        "Users are strongly encouraged to consult qualified professionals before making real-world decisions.\n\n"

        "By typing 'AGREE' and continuing, you acknowledge that you have read, understood, "
        "and accepted these terms and limitations."
    )


def agreement():
    while True:
        type_text(agreement_text())
        choice = input(f"{LIGHT_YELLOW}{BOLD}\nType 'agree' to accept and continue: {RESET}").strip().lower()
        if choice == "agree":
            clear_console()
            return True
        print(f"{RED}You must type 'agree' to continue.{RESET}")
